# Generated by Django 4.0.2 on 2022-04-01 07:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('author_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('preview', models.ImageField(default='../images/default.png', upload_to='')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Имя Фамилия', max_length=30)),
                ('eMail', models.EmailField(max_length=254)),
                ('isBanned', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField()),
                ('photo_path', models.ImageField(upload_to='')),
                ('recept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.user'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('recept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('text_field', models.TextField()),
                ('recept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.recipe')),
            ],
        ),
    ]
