# Generated by Django 4.0.2 on 2022-03-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_user_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author_id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
