# Generated by Django 4.0.2 on 2022-04-30 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(
                auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.user'),
            preserve_default=False,
        ),
    ]
