# Generated by Django 4.0.2 on 2022-03-30 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_recipe_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
