# Generated by Django 4.0.2 on 2022-05-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_comment_id_comment_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship', models.BooleanField(default=False)),
                ('friend_one_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_one_set', to='catalog.user')),
                ('friend_two_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_two_set', to='catalog.user')),
            ],
        ),
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
