# Generated by Django 4.0.2 on 2022-05-09 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_friendlist_delete_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.visitor'),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='friend_one_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_one_set', to='catalog.visitor'),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='friend_two_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_two_set', to='catalog.visitor'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.visitor'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
