# Generated by Django 4.0.2 on 2022-05-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_visitor_alter_comment_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='visitor',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
