# Generated by Django 4.0.2 on 2022-05-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_recipe_date_alter_recipe_preview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preview',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
