# Generated by Django 4.0.2 on 2022-05-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_recipe_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preview',
            field=models.ImageField(default='NULL', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
