# Generated by Django 4.0.2 on 2022-05-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_creator_id_recipe_creator_alter_recipe_date_and_more'),
        ('catalog', '0009_alter_recipe_preview'),
    ]

    operations = [
    ]
