# Generated by Django 4.0.2 on 2022-04-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_step_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='photo_path',
            field=models.ImageField(default='NULL', null=True, upload_to=''),
        ),
    ]
