# Generated by Django 4.0.2 on 2022-05-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_merge_20220523_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preview',
            field=models.ImageField(default='NULL', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
