# Generated by Django 4.0.2 on 2022-07-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_comment_user_id_alter_recipe_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recept_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.recipe'),
            preserve_default=False,
        ),
    ]
