# Generated by Django 4.0.2 on 2022-08-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_comment_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.visitor')),
            ],
        ),
    ]
