# Generated by Django 4.0.2 on 2022-08-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_grade_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('user', 'grade')},
        ),
    ]
